### PR TITLE
Bugfix/log normalisation

### PR DESCRIPTION
**Pull request by siedentop**
I found your BBChop code. Very nice! I tried to run `BBChop/analysis/BBChopTime.py`, and got a crash at `n > 121`. I think, I identified the culprit and found a solution that works. 

Solving the issue of Beta(n, m) becoming 0 for n,m around 680 each.

The solution was to use log(Beta) as long as possible, and when converting log-likelihoods (= Beta * Prior, in likelihoods.py), to first normalise those log-likelihoods by the largest log-likelihood. 

The fault can be detected by running `BBChop/analysis/Makefile` or `BBChop/analysis/regression.py`.

I was not able to test on `multiRate` function, only on the `singleRate` function.

### CODE REVIEW

**Comment by Ealdwulf** [comment]
Thanks! It's been ages since I've touched this code so it may take a while for me to remember how this all works, but I will look at your PR, hopefully at the weekend.

**Comment by siedentop** [comment]
Thanks, too! Let me know if I should explain more.

**Comment by Ealdwulf** [comment]
I haven't had a chance to look at properly yet, I'm sorry. I think the failure is because in `numberType.py` it is using `math.log`/`math.exp` because mppath/decimal did not implement those functions when I wrote it. But your PR is really interesting because maybe we can use native floating point, which would be much faster. 

By the way,  I noticed that you are doing some interesting analysis  in your repo: https://github.com/unapiedra/BBChop/blob/master/analysis/experiment.py#L78
You might want to modify this a bit for low `fail_prob`. The algorithm expects than in a real scenario, you would already have some observations. With no observations it  starts with a uniform prior on `fail_prob`, which is effectively a weak assumption that `fail_prob= 0.5`. So it won't do well with low `fail_prob` because it will read success observations as better evidence that the bug is not in a particular location than they really are. In a real scenario you may know that you are have an intermittent bug if you start to use BBChop, so you'd have some success  and some failure observations for the location of 'HEAD'. If it informed of these, using `finder.`addResult()`, it should work better.

**Comment by siedentop** [comment]
Thank you for your suggestion. I am setting the prior to `1 / N` for every location. And yes that is a too conservative prior. I am going to try your suggestion on Monday or so.

Doing my analysis I've come to three conclusions:
1. The algorithm seems to work. The failure rate of finding a wrong location corresponds well to the requested "certainty". Failure probabilities between 10 and 100 percent result in a useful number of repetitions necessary. Maybe with your suggestion, it is even useful at lower probabilities.
2. I've started to compare it to a naive solution, where a normal bisect is done and each location is tested $k$ times. I choose $k$ such that the overall "certainty" is achieved. This shows me that the naive algorithm has much worse worst-case behaviour than BBChop. (Note: I am comparing theoretical worst-case behaviour against experimental runs of BBChop.) However, the expected behaviour of the naive algorithm is about the same than BBChop. So, I think I will do an experiment on the naive algorithm too.
3. I tried to find examples where this algorithm would be useful in finding this bug. I could not come up with one! (Except for debugging random algorithms like Particle Filters, RANSAC, Monte Carlo-algs, etc). Very often, intermittent failures are not intermittent at all but just occur over a system that is incompletely captured. So, you run the algorithm over a subset of the system (the code) while the real system (the computer) is responsible for the fault. 

If you can think of cases where this algorithm would really help, please let me know! 

But just to be clear, I find the approach quite elegant and would really love to see a good use-case for it.

**Comment by Ealdwulf** [comment]
Thank *you* for this analysis. It's good  to have independent confirmation that the algorithm works. I will be very interested if you make further findings.

You are correct that if a system is completely captured, it is not necessary to resort to this means to fnid a bug. I have been surprised at the progress of reversible debuggers such as undodb, which work to capture all the information necessary to debug a program. They do reduce the cases where BBChop is applicable. I think there are a few of cases where it can be applied.
 In all of the cases, it must be that reversible debuggers cannot for some reason be applied. One reason for this is that such debuggers resort to some heroic means to capture all the data, and there will probably always be corner cases they miss, since the systems they capture were not originally designed to be captured in this way. Another is that since they usually share the resources of the system that they debug, they can't work if they take so many resources that they cause the program to behave differently. Eg, violate its real-time constraints.
Another might be if the program being debugged takes such voluminous real-time input (eg, a chunk of the microwave spectrum) that it is not practical to store it.

These case are not really that exciting, I admit. But the point is that because BBChop makes fewer assumptions, and is less complex, it could be a very worst case fallback where other methods fail.

A more curious case is that, some academics have proposed that to make more efficient use of silicon, we should relax the constraint that we require it to be nearly 100% reliable. Eg, https://www.cs.cornell.edu/~asampson/blog/truffle.html 
Since the non-determinism would then be inherent, quite possibly capturing a program trace would not be sufficient. But I haven't looked into the literature of that. BBChop would need some modification to cope with the fact that 'failure' would no longer be any failure, but a failure rate higher than some threshhold.
Anyway, hope that is of some interest; I apologise for taking such a long time to reply.

**Comment by siedentop** [comment]
Closing because no activity.

**Pull request closed without merging**
